<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HMECD000787" name="com.truaxis.test.reporting.Scenario6Test" tests="7" failures="0" timestamp="29 Nov 2013 15:20:03 GMT" time="0.585" errors="1">
  <testcase name="testRD_6_4" time="0.078" classname="com.truaxis.test.reporting.Scenario6Test"/>
  <testcase name="testRD_6_6" time="0.028" classname="com.truaxis.test.reporting.Scenario6Test"/>
  <testcase name="testRD_6_2" time="0.066" classname="com.truaxis.test.reporting.Scenario6Test">
    <error type="java.lang.AssertionError" message="Export,PDF,Exel,CSV labels,are not displayed on Prepaid Gift Cards Page expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Export,PDF,Exel,CSV labels,are not displayed on Prepaid Gift Cards Page expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at com.truaxis.test.reporting.Scenario6Test.testRD_6_2(Scenario6Test.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testRD_6_2 -->
  <testcase name="testRD_6_1" time="0.036" classname="com.truaxis.test.reporting.Scenario6Test"/>
  <testcase name="testRD_6_7" time="0.269" classname="com.truaxis.test.reporting.Scenario6Test"/>
  <testcase name="testRD_6_3" time="0.051" classname="com.truaxis.test.reporting.Scenario6Test"/>
  <testcase name="testRD_6_5" time="0.057" classname="com.truaxis.test.reporting.Scenario6Test"/>
</testsuite> <!-- com.truaxis.test.reporting.Scenario6Test -->
